#!/bin/sh

chmod +s /Applications/ReportingUI.app/ReportingUI

declare -a cydia
cydia=($CYDIA)

if [[ ${CYDIA+@} ]]; then
	if [ -f /var/log/syslog ];
	then eval "echo 'finish:restart' >&${cydia[0]}";
	else eval "echo 'finish:reboot' >&${cydia[0]}";
	fi
else
	killall SpringBoard
fi

exit 0